# Generated by Django 4.2.9 on 2024-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothes'), ('GR', 'Grip'), ('ACC', 'Accessories')], default='CL', max_length=3),
            preserve_default=False,
        ),
    ]
