# Generated by Django 4.2.9 on 2024-01-12 12:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
